language: r
sudo: required
env:
  os:
    - linux
    - osx
  matrix:
    - RVERSION=devel
    - RVERSION=3.2.0
    - RVERSION=3.3.1
    - RVERSION=3.3.2
notifications:
  email:
    on_success: change
    on_failure: change
